#url: jdbc:mysql://192.168.137.55:3306/user_center
#username: dangjian
#password: uNdvlOK5vMkqU6Xx15vtmEDdxzniQiuE
url: jdbc:mysql://localhost:3306/hierarchical_data_exec
username: root
password: db0723..
driverClassName: com.mysql.jdbc.Driver
attributes:
  serverTimezone: Asia/Shanghai
  useUnicode: true
  characterEncoding: utf8
  allowMultiQueries: true
  useSSL: false
