url: jdbc:mysql://192.168.137.55:3306/user_center
username: dangjian
password: uNdvlOK5vMkqU6Xx15vtmEDdxzniQiuE
driverClassName: com.mysql.jdbc.Driver
attributes:
  serverTimezone: Asia/Shanghai
  useUnicode: true
  characterEncoding: utf8
  allowMultiQueries: true
  useSSL: false
