url: jdbc:mysql://192.168.137.57:3306/leadership_transition
username: dangjian
password: uNdvlOK5vMkqU6Xx15vtmEDdxzniQiuE
driverClassName: com.mysql.jdbc.Driver
attributes:
  serverTimezone: Asia/Shanghai
  useUnicode: true
  characterEncoding: utf8
  allowMultiQueries: true
  useSSL: false
