url: jdbc:mysql://192.168.137.57:3306/user_center
username: dangjian
password: uNdvlOK5vMkqU6Xx15vtmEDdxzniQiuE
#url: jdbc:mysql://192.168.137.59:3306/dangjian
#username: dev
#password: ftbXDnUzyTj6Fvi4
driverClassName: com.mysql.jdbc.Driver
attributes:
  serverTimezone: Asia/Shanghai
  useUnicode: true
  characterEncoding: utf8
  allowMultiQueries: true
  useSSL: false
